// data/projectsData.js

const projects = [
    {
        id: 1,
        title: "Urban Agriculture Project",
        description: "Promoted urban farming by providing free vegetable seeds and seedlings to households, enhancing food security during challenging times.",
        category: "Agriculture",
        icon: "sprout",
        image: "https://www.da.gov.ph/wp-content/uploads/2020/04/IMG_6278-2048x1258.jpg",
        status: "Completed",
        progress: 1.0,
        location: "Muntinlupa City",
        budget: "₱5M",
        stakeholders: ["Local Farmers", "City Government", "Agriculture Department"],
        startDate: "2020-01-15",
        endDate: "2020-12-10"
    },
    {
        id: 2,
        title: "Museo ng Muntinlupa Development",
        description: "Established a museum inspired by the traditional 'salakab' design, showcasing the city's rich cultural heritage.",
        category: "Culture",
        icon: "bank",
        image: "https://muntinlupacity.gov.ph/wp-content/uploads/2023/05/Museo-ng-Muntinlupa-001-Karl-Casanova-1024x683.jpg",
        status: "Completed",
        progress: 1.0,
        location: "Muntinlupa City",
        budget: "₱20M",
        stakeholders: ["City Government", "Local Artists", "Historical Society"],
        startDate: "2019-03-10",
        endDate: "2021-06-15"
    },
    {
        id: 3,
        title: "Community Health Program",
        description: "Provided free medical check-ups and health awareness seminars to improve community well-being.",
        category: "Health",
        icon: "hospital-box",
        image: "https://www.manilatimes.net/manilatimes/uploads/images/2021/06/01/2620.jpg",
        status: "Ongoing",
        progress: 0.75,
        location: "Barangay Tunasan",
        budget: "₱10M",
        stakeholders: ["City Health Office", "Barangay Officials", "Medical Volunteers"],
        startDate: "2022-05-01",
        endDate: "TBD"
    },
    {
        id: 4,
        title: "Scholarship for Students",
        description: "Implemented a scholarship program to support underprivileged students in pursuing education.",
        category: "Education",
        icon: "school",
        image: "https://images.metronewscentral.net/bHw95d2aHp37-munti-achievers.jpg",
        status: "Completed",
        progress: 1.0,
        location: "Muntinlupa City",
        budget: "₱15M",
        stakeholders: ["City Government", "Department of Education", "Private Sponsors"],
        startDate: "2018-07-01",
        endDate: "2022-03-30"
    },
    {
        id: 5,
        title: "Road Infrastructure Development",
        description: "Enhanced roads and bridges to ensure safer and more efficient transportation.",
        category: "Infrastructure",
        icon: "bridge",
        image: "https://metromanila.politiko.com.ph/wp-content/uploads/2021/02/alabang.jpg",
        status: "Ongoing",
        progress: 0.60,
        location: "Alabang-Zapote Road",
        budget: "₱50M",
        stakeholders: ["DPWH", "City Government", "Local Contractors"],
        startDate: "2023-01-10",
        endDate: "TBD"
    },
    {
        id: 6,
        title: "Environmental Awareness Campaign",
        description: "Launched campaigns focusing on clean-up drives and tree-planting activities to promote environmental sustainability.",
        category: "Environment",
        icon: "tree",
        image: "https://images.summitmedia-digital.com/topgear/images/2022/09/06/muntinlupa-city-urban-green-space-and-recreational-park-1662428006.jpg",
        status: "Ongoing",
        progress: 0.85,
        location: "Various Barangays",
        budget: "₱8M",
        stakeholders: ["Environmental Groups", "City Volunteers", "LGU"],
        startDate: "2023-02-01",
        endDate: "TBD"
    },
    {
        id: 7,
        title: "Zero-Interest Loan Program for SMEs",
        description: "Introduced a financial assistance program offering zero-interest loans to small and medium-sized enterprises to boost local entrepreneurship.",
        category: "Economic ",
        icon: "finance",
        image: "https://www.manilatimes.net/manilatimes/uploads/images/2021/11/08/25240.jpg",
        status: "Ongoing",
        progress: 0.50,
        location: "Muntinlupa City",
        budget: "₱30M",
        stakeholders: ["City Government", "Local Entrepreneurs", "Finance Institutions"],
        startDate: "2023-03-15",
        endDate: "TBD"
    },
    {
        id: 8,
        title: "Fire and Rescue Modernization",
        description: "Upgraded the city's emergency response capabilities by acquiring new fire trucks and ambulances, enhancing public safety.",
        category: "Public Safety",
        icon: "fire-truck",
        image: "https://lh5.googleusercontent.com/p/AF1QipPWGHQLMAYcy0yRPHL8zBr2ji89wi0SFfWWzpbC%3Dw1080-k-no",
        status: "Completed",
        progress: 1.0,
        location: "Citywide",
        budget: "₱40M",
        stakeholders: ["Bureau of Fire Protection", "City Disaster Office", "LGU"],
        startDate: "2019-06-01",
        endDate: "2021-12-20"
    },

    {
        id: 9,
        title: "Peace and Order and Public Safety Plan",
        description: "Adopted a comprehensive plan to enhance peace, order, and public safety in Muntinlupa for the years 2020-2022.",
        category: "Governance",
        icon: "shield-account",
        image: "https://ulap.net.ph/vault/images/news/PO1.jpg",
        status: "Completed",
        progress: 1.0,
        location: "Muntinlupa City",
        budget: "₱25M",
        stakeholders: ["PNP", "Barangay Officials", "City Government"],
        startDate: "2020-01-01",
        endDate: "2022-12-31"
    },
    {
        id: 10,
        title: "Comprehensive Local Integration Program Enhancement",
        description: "Enhanced the existing program to facilitate the reintegration of former rebels into the community, promoting peace and development.",
        category: "Social Welfare",
        icon: "account-group",
        image: "https://www.tfbalikloob.gov.ph/Content/Images/banner.png",
        status: "Ongoing",
        progress: 0.70,
        location: "Muntinlupa City",
        budget: "₱12M",
        stakeholders: ["DSWD", "Local Peace Council", "LGU"],
        startDate: "2023-01-01",
        endDate: "2025-12-31"
    }    
];

export default projects;
